"""GenerateDigest use case.

A daily *digest* — a full frontier-model report covering portfolio analytics,
the Congressional signal, and a concrete plan for deploying uninvested cash.
Richer than the congressional-only briefing; generated by a frontier model via
OpenRouter and surfaced as a page on the dashboard, with a Pushover summary
that links to it.

Falls back to a structured template if the model call fails or no OpenRouter
key is configured, so the daily push is never lost.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import UTC, date, datetime, timedelta
from decimal import Decimal
from pathlib import Path
from typing import TYPE_CHECKING

import httpx
from sqlalchemy import select

from trading.adapters.persistence.models import DigestRow, PositionRow, TradeDisclosureRow
from trading.application.signals.generate_briefing import (
    _assess_market_regime,
    _fetch_disclosures,
    _fetch_held_tickers,
)
from trading.domain import AggregateType, DomainEvent, EventType

if TYPE_CHECKING:
    from sqlalchemy.ext.asyncio import AsyncSession

    from trading.application.common.unit_of_work import UnitOfWork
    from trading.application.market_data.refresh_quotes import MarketDataPort

OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"

_SYSTEM_PROMPT = (
    "You are the lead analyst writing a private, institutional-quality DAILY "
    "DIGEST for a sophisticated investor reviewing their OWN portfolio (no "
    "fiduciary/third-party context). Write a full, well-structured markdown "
    "report. Be specific, quantitative, and opinionated — this is for the "
    "owner's own decisions. Required sections, in order:\n"
    "1. ## TL;DR — 3-4 bullets, the single most important things today.\n"
    "2. ## Portfolio Snapshot — value, cash, and concentration risk. Call out "
    "any single position that is an outsized share of the book.\n"
    "3. ## Congressional Signal — read the disclosures: who's buying/selling "
    "what, conviction (dollar size), disclosure lag, and which (if any) "
    "intersect the holdings. Separate noise from genuine signal.\n"
    "4. ## Deploying the Cash — a concrete, staged allocation plan for the "
    "uninvested cash: specific tickers/sleeves, rough dollar amounts or %, "
    "entry approach (lump vs DCA), and the thesis for each. Respect existing "
    "concentration. It is acceptable to recommend holding some/all in cash if "
    "that's the honest call.\n"
    "5. ## Risk & Watch Items — what could go wrong, what to monitor.\n"
    "6. ## Action of the Day — ONE clear call, actionable in the SELF-DIRECTED "
    "account only: BUY <ticker> / deploy cash, or HOLD. HOLD is valid; never "
    "invent a trade.\n"
    "End with a line 'PUSH: ' then a 2-3 sentence phone-notification summary "
    "that leads with the action and teases the digest.\n"
    "\n"
    "HARD CONSTRAINTS — obey strictly:\n"
    "- The JOINT account is BROKER/ADVISOR-MANAGED. The owner CANNOT liquidate "
    "it. NEVER recommend selling or trimming any joint/managed position — treat "
    "them as fixed (hold-only). You may discuss their concentration as risk to "
    "be aware of, but the remedy is NOT a sale.\n"
    "- TAX: the owner already realized a large capital gain THIS YEAR (a ~$200k "
    "position was sold). Do NOT recommend realizing further gains in any taxable "
    "account; additional appreciated-stock sales stack capital-gains tax.\n"
    "- All deployment and any BUY actions apply ONLY to the self-directed "
    "individual account and its available cash. The Action of the Day must be "
    "something the owner can actually execute there.\n"
    "Do not hedge with generic disclaimers; be direct and useful."
)


@dataclass(frozen=True, slots=True)
class _Pos:
    sym: str
    qty: Decimal
    mv: Decimal
    pnl: Decimal


@dataclass(frozen=True, slots=True)
class _Account:
    name: str
    managed: bool
    cash: Decimal
    positions: list[_Pos]


_DATA_DIR = Path(__file__).resolve().parents[4] / "data"


def _load_account_file(filename: str) -> _Account | None:
    """Load an account holdings file (joint or individual) for digest context —
    its cash, managed flag, and positions. Returns None if absent/unreadable."""
    path = _DATA_DIR / filename
    if not path.exists():
        return None
    try:
        d = json.loads(path.read_text())
    except (OSError, ValueError):
        return None
    positions = [
        _Pos(
            sym=h["symbol"],
            qty=Decimal(str(h.get("quantity", "0"))),
            mv=Decimal(str(h.get("market_value", "0"))),
            pnl=Decimal(str(h.get("unrealized_pnl", "0"))),
        )
        for h in d.get("holdings", [])
    ]
    return _Account(
        name=str(d.get("nickname", filename)),
        managed=bool(d.get("managed", False)),
        cash=Decimal(str(d.get("cash", "0"))),
        positions=positions,
    )


@dataclass(frozen=True, slots=True)
class GenerateDigestCommand:
    correlation_id: object  # UUID
    actor: str
    for_date: date | None = None


@dataclass(frozen=True, slots=True)
class DigestContent:
    digest_id: str
    digest_date: date
    summary_markdown: str
    push_excerpt: str
    model: str
    net_liquidation: str
    cash_to_deploy: str
    disclosures_count: int
    generated_by: str  # "openrouter" | "template"
    generated_at: datetime


async def execute(
    cmd: GenerateDigestCommand,
    uow: UnitOfWork,
    *,
    market_data: MarketDataPort | None = None,
    openrouter_api_key: str = "",
    model: str = "anthropic/claude-opus-4.8",
    cash_to_deploy: str = "0",
) -> DigestContent:
    """Generate + persist the daily digest."""
    now = uow.clock.now()
    session = uow.session
    target_date = cmd.for_date or now.date()

    period_end = datetime.combine(target_date + timedelta(days=1), datetime.min.time(), tzinfo=UTC)
    period_start = period_end - timedelta(days=45)

    disclosures = await _fetch_disclosures(session, period_start, period_end)
    held = await _fetch_held_tickers(session)
    overlaps = [d for d in disclosures if d.symbol and d.symbol in held]
    positions = await _fetch_positions(session)
    regime = await _assess_market_regime(market_data)

    # Account context: the joint book (DB positions) is broker-managed; the
    # self-directed individual account holds the deployable cash.
    joint = _load_account_file("holdings.json")
    individual = _load_account_file("holdings-individual.json")
    joint_managed = bool(joint and joint.managed)
    if individual is not None:
        cash_to_deploy = str(individual.cash)  # real cash, not a constant

    total_sec = sum((p.mv for p in positions), Decimal("0"))
    context = _build_context(
        target_date, positions, total_sec, disclosures, overlaps, regime,
        cash_to_deploy, individual, joint_managed,
    )

    generated_by = "template"
    summary = _template_digest(
        positions, total_sec, disclosures, overlaps, cash_to_deploy, joint_managed
    )
    push = _template_push(target_date, disclosures, overlaps)

    if openrouter_api_key:
        try:
            md, excerpt = await _call_openrouter(context, openrouter_api_key, model)
            if md and len(md) > 200:  # reject empty / truncated responses
                summary, push, generated_by = md, (excerpt or push), "openrouter"
        except Exception:  # noqa: BLE001 — never let the daily push die on the model
            pass

    model_used = model if generated_by == "openrouter" else "template"
    digest_id = f"digest-{target_date.isoformat()}-{_short_id(now)}"
    net_liq = str(total_sec.quantize(Decimal("0.01")))
    session.add(
        DigestRow(
            digest_id=digest_id,
            digest_date=datetime.combine(target_date, datetime.min.time(), tzinfo=UTC),
            summary_markdown=summary,
            push_excerpt=push,
            model=model_used,
            net_liquidation=net_liq,
            cash_to_deploy=cash_to_deploy,
            disclosures_count=len(disclosures),
            body_blob_key=None,
            generated_at=now,
        )
    )

    uow.collect(
        DomainEvent(
            type=EventType.BRIEFING_PRODUCED,
            aggregate_id=digest_id,
            aggregate_type=AggregateType.BRIEFING,
            payload={
                "digest_id": digest_id,
                "digest_date": target_date.isoformat(),
                "disclosures_count": len(disclosures),
                "portfolio_overlaps": len(overlaps),
                "generated_by": generated_by,
                "model": model_used,
            },
        )
    )

    return DigestContent(
        digest_id=digest_id,
        digest_date=target_date,
        summary_markdown=summary,
        push_excerpt=push,
        model=model_used,
        net_liquidation=net_liq,
        cash_to_deploy=cash_to_deploy,
        disclosures_count=len(disclosures),
        generated_by=generated_by,
        generated_at=now,
    )


def _short_id(now: datetime) -> str:
    """Deterministic 8-char suffix from the timestamp (no Math.random equiv. in
    the domain; uniqueness within a day is sufficient since the latest wins)."""
    return f"{int(now.timestamp()):08x}"[-8:]


# --- Data ---------------------------------------------------------------------


async def _fetch_positions(session: AsyncSession) -> list[_Pos]:
    rows = (
        (await session.execute(select(PositionRow).order_by(PositionRow.market_value.desc())))
        .scalars()
        .all()
    )
    positions = [
        _Pos(
            sym=r.symbol,
            qty=Decimal(str(r.quantity)),
            mv=Decimal(str(r.market_value)),
            pnl=Decimal(str(r.unrealized_pnl)),
        )
        for r in rows
    ]
    positions.sort(key=lambda p: -p.mv)
    return positions


def _build_context(
    target_date: date,
    positions: list[_Pos],
    total_sec: Decimal,
    disclosures: list[TradeDisclosureRow],
    overlaps: list[TradeDisclosureRow],
    regime: str,
    cash_to_deploy: str,
    individual: _Account | None,
    joint_managed: bool,
) -> str:
    def pct(mv: Decimal) -> str:
        return f"{(mv / total_sec * 100):.1f}%" if total_sec else "0%"

    top_lines = "\n".join(
        f"| {p.sym} | ${p.mv:,.0f} | {pct(p.mv)} | {p.pnl:+,.0f} |" for p in positions[:15]
    )
    disc_lines = []
    for d in disclosures[:40]:
        lo, hi = d.amount_range_low, d.amount_range_high
        amt = f"${int(lo):,}–${int(hi):,}" if lo and hi else "??"
        disc_lines.append(
            f"| {d.member_name} | {d.symbol or '?'} | {d.transaction_type} | {amt} | "
            f"{d.transaction_date.date()} | {d.disclosure_date.date()} |"
        )
    overlap_syms = sorted({d.symbol for d in overlaps if d.symbol})

    joint_label = (
        "BROKER/ADVISOR-MANAGED — owner cannot liquidate; HOLD-ONLY, never recommend "
        "selling these; tax-sensitive (large gain already realized this year)"
        if joint_managed
        else "self-directed"
    )
    indiv_line = "Individual (self-directed): not loaded."
    if individual is not None:
        held = ", ".join(f"{p.sym} {p.qty:g}" for p in individual.positions) or "none"
        indiv_line = (
            f"Individual (SELF-DIRECTED — deploy/trade here): "
            f"${individual.cash:,.0f} cash; positions: {held}."
        )

    return (
        f"ACCOUNTS:\n"
        f"- Joint (the book below): {joint_label}.\n"
        f"- {indiv_line}\n\n"
        f"JOINT PORTFOLIO (managed book — context only, NOT tradeable):\n"
        f"- Book value: ${total_sec:,.0f} across {len(positions)} positions\n"
        f"- Top positions (| Ticker | Mkt Value | % of book | Unrealized P/L |):\n"
        f"| Ticker | Mkt Value | % book | Unrl P/L |\n|---|---|---|---|\n{top_lines}\n\n"
        f"CASH TO DEPLOY (self-directed account): ${Decimal(cash_to_deploy):,.0f}\n\n"
        f"RECENT CONGRESSIONAL DISCLOSURES (newest first):\n"
        f"| Member | Ticker | Action | Amount | Traded | Disclosed |\n|---|---|---|---|---|---|\n"
        + "\n".join(disc_lines)
        + f"\n\nDISCLOSURES OVERLAPPING HELD TICKERS: {', '.join(overlap_syms) or 'none'}\n"
        f"MARKET REGIME: {regime}\nDATE: {target_date.isoformat()}\n"
    )


async def _call_openrouter(context: str, api_key: str, model: str) -> tuple[str, str]:
    async with httpx.AsyncClient(timeout=180.0) as client:
        resp = await client.post(
            OPENROUTER_URL,
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
                "HTTP-Referer": "https://trackdash.example.com",
                "X-Title": "Tracker Daily Digest",
            },
            json={
                "model": model,
                "max_tokens": 6000,
                "messages": [
                    {"role": "system", "content": _SYSTEM_PROMPT},
                    {"role": "user", "content": context},
                ],
            },
        )
        resp.raise_for_status()
        text: str = resp.json()["choices"][0]["message"]["content"]
    push = ""
    if "PUSH:" in text:
        head, tail = text.rsplit("PUSH:", 1)
        text, push = head.rstrip(), tail.strip()
    return text, push


# --- Template fallback --------------------------------------------------------


def _template_digest(
    positions: list[_Pos],
    total_sec: Decimal,
    disclosures: list[TradeDisclosureRow],
    overlaps: list[TradeDisclosureRow],
    cash_to_deploy: str,
    joint_managed: bool,
) -> str:
    managed_note = (
        " (broker-managed, hold-only)" if joint_managed else ""
    )
    lines = [
        "# Daily Digest",
        "",
        "## Portfolio Snapshot",
        "",
        f"- Joint book value{managed_note}: **${total_sec:,.0f}** across {len(positions)} positions",
        f"- Cash to deploy (self-directed): **${Decimal(cash_to_deploy):,.0f}**",
        "",
        "| Ticker | Market Value | % of book | Unrealized P/L |",
        "|--------|-------------|-----------|----------------|",
    ]
    for p in positions[:15]:
        share = f"{(p.mv / total_sec * 100):.1f}%" if total_sec else "0%"
        lines.append(f"| {p.sym} | ${p.mv:,.0f} | {share} | {p.pnl:+,.0f} |")
    overlap_syms = sorted({d.symbol for d in overlaps if d.symbol})
    lines += [
        "",
        "## Congressional Signal",
        "",
        f"{len(disclosures)} disclosure(s) in the window; "
        f"{len(overlaps)} touch your holdings ({', '.join(overlap_syms) or 'none'}).",
        "",
        "## Action of the Day",
        "",
        "**HOLD** — frontier model unavailable, so no automated recommendation today. "
        "Review the holdings and disclosures above manually.",
    ]
    return "\n".join(lines)


def _template_push(
    target_date: date, disclosures: list[TradeDisclosureRow], overlaps: list[TradeDisclosureRow]
) -> str:
    return (
        f"📊 {target_date.isoformat()} — Action: HOLD. "
        f"{len(disclosures)} disclosure(s), {len(overlaps)} overlap(s) with your book. "
        "Full digest on trackdash."
    )
