apiVersion: v1
kind: Secret
metadata:
  name: tracker-secrets
  namespace: tracker
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://tracker:trackerpass@tracker-postgres.tracker.svc.cluster.local:5432/tracker
  BROKER_MODE: fake
  ALLOW_LIVE_TRADING: "false"
  MASSIVE_API_KEY: CiJ1GJp9cwuekTiqsjmbFz45JWlPduJm
  QUIVER_API_KEY: 428c3bef28754d355fadeeb6eb875d09884e5645
  LLM_PROVIDER: litellm
  LLM_API_KEY: sk-litellm-spike-9f3a2c7e1b
  LLM_MODEL: local-fast
  LITELLM_BASE_URL: http://litellm.local-ai.svc.cluster.local:4000
  PUSH_PROVIDER: pushover
  PUSHOVER_API_TOKEN: a94m76y61gvrpb7ury7kkr1x9nm1cb
  PUSHOVER_USER_KEY: umjwuzaienjis5orojeu5odrudtmdw
  POSTGRES_PASSWORD: trackerpass
